export enum ProviderName {
    ENV_CONFIG = 'ENV_CONFIG',
    CMS_SERVICE = 'CMS_SERVICE',
    CMS_REPOSITORY = 'CMS_REPOSITORY',
    HTTP_CLIENT = 'HTTP_CLIENT',
    REQUEST_CONTEXT = 'REQUEST_CONTEXT',

    AUTH_REPOSITORY = 'AUTH_REPOSITORY',
    LOCALE_REPOSITORY = 'LOCALE_REPOSITORY',

    CACHE_SERVICE = 'CACHE_SERVICE'
}