export enum ProviderName {
    ENV_CONFIG = 'ENV_CONFIG',
    CMS_SERVICE = 'CMS_SERVICE',
    CMS_REPOSITORY = 'CMS_REPOSITORY',

    AUTH_REPOSITORY = 'AUTH_REPOSITORY',
    LOCALE_REPOSITORY = 'LOCALE_REPOSITORY',
}